# Generated by Django 6.0.4 on 2026-04-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
