# Generated by Django 6.0.4 on 2026-05-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0002_customer_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_management_app.seller'),
            preserve_default=False,
        ),
    ]
