# Generated by Django 6.0.4 on 2026-05-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
